# Generated by Django 4.2.2 on 2023-06-22 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_No', models.IntegerField()),
                ('Full_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('Age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(17)])),
                ('Class', models.CharField(choices=[(1, '1st Grade'), (2, '2nd Grade'), (3, '3rd Grade'), (4, '4th Grade'), (5, '5th Grade'), (6, '6th Grade'), (7, '7th Grade'), (8, '8th Grade'), (9, '9th Grade'), (10, '10th Grade'), (11, '11th Grade'), (12, '12th Grade')], max_length=10)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('Marklist', models.FileField(upload_to='files/')),
            ],
        ),
    ]
